### ISSUE TITLE
Add a prompt to ask the user to whether 

### ISSUE THREAD

**Issue by chrisli30** [OAK-Foundation/xcm-demo#32]
In dev environment of Mangata and Shibuya, before schedule a job we need to ask the user to choose from trigger immediately vs wait for an hour. Please add that prompt to give the program runner both options in dev. We already have the code for both options.

The select code demo can be found in src/utils.js

```
   const actionSelected = await select({
        message: 'Select an action to perform',
        choices: actions,
    });
```

The fee calcuation seems to differ between the two methods, I tried to use immediate schedule with `{ Fixed: { executionTimes: [0] } }`, but got the below error
![CleanShot 2023-02-08 at 11 38 50](https://user-images.githubusercontent.com/2616844/217634253-6d97dbd1-cf9e-4346-8af2-a0963a6751ea.png)

**Comment by imstar15** [comment]
_The fee calcuation seems to differ between the two methods, I tried to use immediate schedule with { Fixed: { executionTimes: [0] } }, but got the below error_



```
shibuyaHelper.api.tx.dappsStaking.claimStaker({
    Evm: '0x1cee94a11eaf390b67aa346e9dda3019dfad4f6a',
});
```


After testing, it is caused by `dappsStaking.claimStaker` call.

This problem does not occur if you use `system.remarkWithEvent`.

I'm working on it.
